<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.1-dev INSTALLER - Wednesday 30th of April 2014 04:31:44 AM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return
	array(
		"base_url" => "http://svcampaign.com/ProjectTemplate/src/user/login/oauth",

		"providers" => array (
			// openid providers
			"OpenID" => array (
				"enabled" => false
			),

			"AOL"  => array (
				"enabled" => false
			),

			"Yahoo" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "1041702881530-qlum472jhm7qbm77t3nbd4nl2is4hmv0.apps.googleusercontent.com", "secret" => "fU70qiFxQbBPGDDfqt30mb9M" )
			),

			"Facebook" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "1466308250271202", "secret" => "7ae20177662a17763cd79ca17c3e2c7c" ),
				"display" => 'popup'
			),

			"Twitter" => array (
				"enabled" => true,
				"keys"    => array ( "key" => "MCZS8Z8NC9YBSGUmItKDqwzuf", "secret" => "7Vw1L1xjy1t9CqzAr2uJJcQeTNSyLNMeOKjCYGZdCEVbygfgZY" )
			),

			// windows live
			"Live" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"MySpace" => array (
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" )
			),

			"LinkedIn" => array (
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" )
			),

			"Foursquare" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
